name: Rust
on:
  push:
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Install rust semantic-release
        run: cargo install semantic-release-rust --version 1.0.0-alpha.8
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/exec
      # - name: Build and upload Rust binary to GitHub Releases
      #   uses: taiki-e/upload-rust-binary-action@v1.12.0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

